### ISSUE TITLE
Server under windows crashes after logout from terminal session

### ISSUE THREAD

**Issue by michaldziwisz** [Technow-es/NVDARemoteServer#1]
Hi,
server is hosted on win 7 X64. When some clients are connected and disconnect normaly, all works fine. When somebody is loging into win 2003 or 2008 server, do something and press logout, server is closing without any errors or warnings. This happens even when I am using a service version too.

**Comment by jmdaweb** [comment]
Hi.
Run the application from a console, instead of opening it from windows explorer. The error will appear before the application closes, and you will be able to see and copy it.


From: michaldziwisz 
Sent: Tuesday, July 7, 2015 2:09 AM
To: Technow-es/NVDARemoteServer 
Subject: [NVDARemoteServer] Server under windows crashes after logout from terminal session (#1)

Hi,
server is hosted on win 7 X64. When some clients are connected and disconnect normaly, all works fine. When somebody is loging into win 2003 or 2008 server, do something and press logout, server is closing without any errors or warnings. This happens even when I am using a service version too.

**Comment by michaldziwisz** [comment]
Ok, so here it is:
C:\nvda_srv>nvdaremoteserver.exe
Traceback (most recent call last):
  File "server.py", line 178, in <module>
  File "server.py", line 50, in run
  File "server.py", line 98, in handle_data
  File "ssl.pyo", line 241, in recv
  File "ssl.pyo", line 160, in read
socket.error: [Errno 10054] Istniej?ce po-?czenie zosta-o gwa-townie zamkni�te p
rzez zdalnego hosta

**Comment by jmdaweb** [comment]
Could you please translate the error message into english with your own words? I am using google translate and I don’t understand anything.

**Comment by michaldziwisz** [comment]
An existing connection was forcibly closed by the remote host.

**Comment by jmdaweb** [comment]
I have captured the exception. Now, if a client fails, its connection is closed.
